name: Build STM32 Firmware

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi ninja-build cmake make

      - name: Configure project with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-arm-none-eabi.cmake

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Upload firmware artifact (.elf)
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/lfly.elf
